/*
 * This source file was generated by the Gradle 'init' task
 */
package drawingproject;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        @SuppressWarnings("unused")
        Runner classUnderTest = new Runner();
    }
}
